services:
  docusaurus:
    image: cloudseidoranalytics/portal:ee037fb6337e56db8cb69a3f4682faf65e77b17b
    # IMPORTANTE: No añadir sección 'build' aquí. 
    # La imagen se construye en GitHub Actions y Portainer solo debe descargarla (PULL).
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped
