services:
  docusaurus:
    image: cloudseidoranalytics/portal:1458b1460f7e07b4742fad5b4761ff9727cdcd09
    # IMPORTANTE: No añadir sección 'build' aquí. 
    # La imagen se construye en GitHub Actions y Portainer solo debe descargarla (PULL).
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped
