services:
  docusaurus:
    image: cloudseidoranalytics/portal:bbfb2d17b3dfe8fe81af267afadb17e9fd515675
    # IMPORTANTE: No añadir sección 'build' aquí. 
    # La imagen se construye en GitHub Actions y Portainer solo debe descargarla (PULL).
    ports:
      - "3050:80"  # Solo HTTP, Nginx Proxy Manager hace el TLS
    restart: unless-stopped
