// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {

  tutorialSidebar: [],
  crestoneSidebar: [{ type: 'autogenerated', dirName: 'crestone' }],
  daianaSidebar: [{ type: 'autogenerated', dirName: 'daiana' }],
  doxaSidebar: [{ type: 'autogenerated', dirName: 'doxa' }],
  ccSidebar: [{ type: 'autogenerated', dirName: 'cc' }],
  harbingerSidebar: [{ type: 'autogenerated', dirName: 'harbinger' }],
  feelingsSidebar: [{ type: 'autogenerated', dirName: 'feelings' }],
  successfactorsSidebar: [],
  businessone: [{ type: 'autogenerated', dirName: 'businessoneanalytics' }],
  bydesign: [{ type: 'autogenerated', dirName: 'bydesign' }],
  s4hanaanalytics: [{ type: 'autogenerated', dirName: 's4hanaanalytics' }],
  planning: [],
  admin: [{ type: 'autogenerated', dirName: 'admin' }],
  portal: [{ type: 'autogenerated', dirName: 'portal' }],
};

export default sidebars;
