// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [],
  crestoneSidebar: [{type: 'autogenerated', dirName: 'crestone'}],
  daianaSidebar: [{type: 'autogenerated', dirName: 'daiana'}],
  doxaSidebar:[{type: 'autogenerated', dirName: 'doxa'}],
  ccSidebar:[{type: 'autogenerated', dirName: 'cc'}],
  harbingerSidebar:[{type: 'autogenerated', dirName: 'harbinger'}],
  feelingsSidebar:[{type: 'autogenerated', dirName: 'feelings'}],
  successfactorsSidebar:[{type: 'autogenerated', dirName: 'successfactors'}],
  businessone: [{type: 'autogenerated', dirName: 'successfactors'}],
  bydesign: [{type: 'autogenerated', dirName: 'successfactors'}],
  s4hanaanalytics: [{type: 'autogenerated', dirName: 'successfactors'}],
  planning: [{type: 'autogenerated', dirName: 'successfactors'}],
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
